### ISSUE TITLE
EdgeHTML version and App version

### ISSUE THREAD

**Issue by Ezyweb-uk** [Wolfcast/BrowserDetection#10]
getVersion for MS Edge is reporting 13.10586  whereas it's actually showing 25.10586.0.0 from the browser help>about section. I see that from https://en.wikipedia.org/wiki/Microsoft_Edge 13.10586 matches the 'EdgeHTML version' which appears to be the underlying browser platform version whereas 25.x is the app version that the user sees. Are we able to return app version? It doesn't look likely since I've read that the app version is not in the UA string.

I wanted to label this as a question but couldn't see how to do that.

**Comment by Wolfcast** [comment]
Since it's not already in the UA string the only thing we can do to show the "about" version would be to maintain a conversion table. I might do this since I already did it for earlier Safari versions.

**Comment by Wolfcast** [comment]
With the new Edge based on Chromium which use the correct version in the UA, I don't see a point in implementing this now.
