### ISSUE TITLE
Samsung browser on Android 5 detected as Chrome 34

### ISSUE THREAD

**Issue by nickwuk** [Wolfcast/BrowserDetection#12]
Samsung browser on Android 5 detected as Chrome 34 on unknown operating system.

**Comment by Wolfcast** [comment]
Can you provide the User Agent string for that browser/device so I can look into this?

**Comment by nickwuk** [comment]
Thanks for commenting on my 3 posts. When tested on Samsung browser on Galaxy S4 the Php variable $_SERVER['HTTP_USER_AGENT'] returns the following:
Mozilla/5.0 (Linux; Android 5.0.1; SAMSUNG GT-I9505 Build/LRX22C) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/34.0.1847.76 Mobile Safari/537.36

**Comment by Wolfcast** [comment]
Support for the Samsung Browser and for Android versions numbers and names will be added soon.

**Comment by Wolfcast** [comment]
Samsung Internet browser and Android version (# & name) now live in release 2.4.0.
