### ISSUE TITLE
Add Vivaldi Browser

### ISSUE THREAD

**Issue by 20Fourteen** [Wolfcast/BrowserDetection#13]
Hi,

Is it possible to add the Vivaldi browser?

https://vivaldi.com/
http://thadafinser.github.io/UserAgentParserComparison/v5/user-agent-detail/b8/16/b816ebe2-1b59-43ff-8ee1-ef672e023f4c.html
https://www.whatismybrowser.com/developers/tools/user-agent-parser/browse/browser-name/vivaldi-user-agents

Thanks!

**Comment by Wolfcast** [comment]
Support for Vivaldi is now added in version 2.4.0.

**Comment by Wolfcast** [comment]
Vivaldi support has been removed from the native detection in version 2.9.0 (out now). You can re-enable it easily like this:
```
$browser = new Wolfcast\BrowserDetection();
$browser->addCustomBrowserDetection('Vivaldi');
```
