### ISSUE TITLE
Not detecting 64-bit Linux

### ISSUE THREAD

**Issue by half-fast** [Wolfcast/BrowserDetection#14]
While using Ubuntu 15.10 64-bit, the detection script displays False for Platform is 64-bit.

**Comment by ThaDafinser** [comment]
@half-fast can u provide a useragent?

**Comment by Wolfcast** [comment]
I can reproduce it and it's a very simple fix. Will fix in next release.

**Comment by half-fast** [comment]
My apologies for not getting back.  Off work due to an injury.

**Comment by Wolfcast** [comment]
Fixed in version 2.5.1. If you still have the issue let me know.
