### ISSUE TITLE
Request : Add SSL/TLS Support

### ISSUE THREAD

**Issue by tejas511** [Wolfcast/BrowserDetection#20]
Hello,

Most of modern browser support SSL and TLS. Now only issue is at time of development, we need to check version for payment gateways. If you can add feature of SSL and TLS support like supports TLS1.2 or TLS1.1 then your class will be unique compare to others.

**Comment by Wolfcast** [comment]
Not sure how you can detect that from the User Agent? Can you be more specific on what are your needs?

**Comment by Wolfcast** [comment]
Closing as not details has been given. Add comments here so I can see if we reopen this.
