### ISSUE TITLE
Add macOS High Sierra

### ISSUE THREAD

**Issue by jimmyadaro** [Wolfcast/BrowserDetection#21]
Last version of macOS reachs until macOS Sierra (10.12), since September 2017 we have available High Sierra (10.13) but has not been added to the `macVerToStr` function.

https://en.wikipedia.org/wiki/OS_X#Release_history

May someone please add it?

**Comment by Wolfcast** [comment]
It's already added in the upcoming release. Look for it in the next commit.

**Comment by Wolfcast** [comment]
Sorry for the long delay but it's included in version 2.9.0 which is out now! Will get minor updates out more often in the future while the bigger release are in the works.
