### ISSUE TITLE
Missing information for Jolla and Sailfish OS

### ISSUE THREAD

**Issue by DestructionOfPlanetJupiter** [Wolfcast/BrowserDetection#22]
That would be the result of the __toString method of PHP:

<strong>User agent:</strong> Mozilla/5.0 (Maemo; Linux; U; Sailfish; Mobile; rv:38.0) Gecko/38.0 Firefox/38.0 SailfishBrowser/1.0
<strong>Browser name:</strong> Firefox
<strong>Browser version:</strong> 38.0
<strong>Platform family:</strong> Linux
<strong>Platform version:</strong> unknown
<strong>Platform version name:</strong> unknown
<strong>Platform is 64-bit:</strong> false
<strong>Is mobile:</strong> false
<strong>Is robot:</strong> false
<strong>IE is in compatibility view:</strong> false
<strong>Emulated IE version:</strong> Not applicable
<strong>Is Chrome Frame:</strong> false
<strong>Is AOL optimized:</strong> false
<strong>AOL version:</strong> Not applicable

I have the first edition of a Jolla phone and I do not know how this looks like with a Jolla C or one of those rare Jolla tables that might be in circulation. I am not sure whether there would be a difference.

**Comment by Wolfcast** [comment]
With version 2.9.0 you can easily add support with:
```
$browserDetect->addCustomPlatformDetection('Sailfish', 'Sailfish', true);
```
