### ISSUE TITLE
Opera is detected to be Chrome!!

### ISSUE THREAD

**Issue by Spiracle** [Wolfcast/BrowserDetection#27]
my Opera 54 is detected to be Chrome. Updating to 57 did not help. (OS: Win10/64bit)

**Comment by mimmi20** [comment]
Please add a useragent.

**Comment by Wolfcast** [comment]
Thanks for the report. It seems Opera changed it's UA recently. I will fix this in the next release (very soon).

**Comment by Wolfcast** [comment]
Fixed with Version 2.9.2 which is out now!

**Comment by htmgarcia** [comment]
Opera for iPad (6th generation) detected as Safari.
