### ISSUE TITLE
edge on android

### ISSUE THREAD

**Issue by blue-eyed-devil** [Wolfcast/BrowserDetection#28]
Edge v42 on Android is detected as Chrome v71

**Comment by Wolfcast** [comment]
Can you provide with the user agent please?

**Comment by blue-eyed-devil** [comment]
Mozilla/5.0 (Linux; Android 8.1.0; ASUS_X00TD) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36 EdgA/42.0.92.3350

**Comment by Wolfcast** [comment]
Confirmed. Will fix this week.

**Comment by Wolfcast** [comment]
Fixed in 2.9.3 (released just now).
