### ISSUE TITLE
Filtering HTTP_USER_AGENT

### ISSUE THREAD

**Issue by uwereiher** [Wolfcast/BrowserDetection#29]
Instead of: `$agentString = $_SERVER['HTTP_USER_AGENT'];` on line 619 I would suggest `$agentString = filter_input(INPUT_SERVER, 'HTTP_USER_AGENT', FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW)` to prevent code injection and follow the PHP guidelines about access to global variables.

**Comment by Wolfcast** [comment]
Added in 2.9.3 (released just now). Thanks for the suggestion!
