### ISSUE TITLE
Not following Semantic Versioning crashes our applications

### ISSUE THREAD

**Issue by halloei** [Wolfcast/BrowserDetection#31]
In the past, my application crashed because you've made a breaking change in a minor version (from 2.5.1 to 2.9.0). Since then I've locked your package at 2.9.*, hoping this would never happen again.

With 2.9.5 you've released breaking changes in a patch version. If I didn't looked that up because of my experience with version 2.9.0, my application would have been crashed again.

Please, follow the semantic versioning pattern ( https://semver.org/ ) in the future!

**Comment by Wolfcast** [comment]
Sorry about that. Will take that into consideration in the future.

**Comment by halloei** [comment]
Thanks! And thank you for your package!
