### ISSUE TITLE
Chrome OS falsely detected as Android platform.

### ISSUE THREAD

**Issue by Robzilla-87** [Wolfcast/BrowserDetection#33]
Hi, I should start by saying I'm a complete noob so I'm sorry if my inexperience shows here.

When I visit your [demo page](https://wolfcast.com/open-source/browser-detection/tutorial.php) from a Chromebook (Lenovo C330) in Chrome, the platform family shows as Android. I was expecting it to show up as Chrome OS. It correctly identified the other platforms I tested (Android, iOS, Mac and Windows).

Is this result unavoidable due to the nature of Chrome OS? Or is it something you could add support for?

Thanks for making an otherwise awesome project that even my inexperienced self was able to add to my site. :)

**Comment by Wolfcast** [comment]
Can you please post the user agent of the device. With it I will be able to answer your question (and fix the detection if it's wrong). Thanks for the kind words!

**Comment by Robzilla-87** [comment]
You get top marks for a quick reply, too!

User agent: Mozilla/5.0 (Linux; Android 9; Mediatek MT8173 Chromebook Build/R81-12871.102.0; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Safari/537.36 [FB_IAB/FB4A;FBAV/274.0.0.46.119;]

**Comment by Wolfcast** [comment]
This is now implemented in [version 2.9.6](https://github.com/Wolfcast/BrowserDetection/releases/tag/2.9.6). Sorry for the long delay!
