### ISSUE TITLE
Question about licence

### ISSUE THREAD

**Issue by wnnawalaniec** [Wolfcast/BrowserDetection#34]
Hi, this library seems like a ton of great work. I was considering using it, but unfortunately GPL licence makes it not possible in most commercial projects. Original Chris's library was MIT and I wonder if it was your intention?

**Comment by Wolfcast** [comment]
I have to confess that when I picked LGPL3 8 years ago I was not too familiar with it's restrictions. No it was not my intention and never have to review it since you are my fist comment about the license :) I will switch to dual licence LGPL3 or MIT later today.

**Comment by wnnawalaniec** [comment]
That's great news, thanks! 🙏

**Comment by Wolfcast** [comment]
Changes published with version 2.9.7: https://github.com/Wolfcast/BrowserDetection/releases/tag/2.9.7

**Comment by htmgarcia** [comment]
Sorry for my ignorance. A “GPLv2 or later” license software can use this library?
