### ISSUE TITLE
How can I detect the platform version?

### ISSUE THREAD

**Issue by zeckdude** [Wolfcast/BrowserDetection#5]
Is there any way I can detect what version of the platform the user has? Currently it will tell me the platform, but I would like to know the exact version of the platform as well.

**Comment by Wolfcast** [comment]
Not for the moment. For Windows i would be relatively easy to implement but for other platforms the scheme vary quite a lot (when populated in the user agent) and would be largely unreliable.

**Comment by Wolfcast** [comment]
You can now get the platform version with version 2.3. At the moment only Windows operating systems are supported (from Windows 3.1 to Windows 10 - including server "flavors").
