### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by BassemN** [Wolfcast/BrowserDetection#7]
Hi,
Great PHP class :+1: 
Are you planning to add your class to https://packagist.org/ to make your class simple to install and update?

**Comment by Wolfcast** [comment]
I will look into that.

**Comment by DelightedD0D** [comment]
Composer support would be great. Nice class!

**Comment by ThaDafinser** [comment]
Also waiting for composer support :+1:

**Comment by bensinclair** [comment]
+1 It's really easy. They have a section on the Packagist [home page](https://packagist.org/) about what to do and how to publish.

**Comment by Wolfcast** [comment]
Sorry for the answer delay! Support for Packagist should be added. Can you confirm it works as expected on your side?

**Comment by bensinclair** [comment]
Hmm I'm receiving the following error when I run `composer require wolfcast/browser-detection`. I even copied it from https://packagist.org/packages/wolfcast/browser-detection

` [InvalidArgumentException]                                                   
  Could not find package wolfcast/browser-detection at any version for your m  
  inimum-stability (stable). Check the package spelling or your minimum-stabi  
  lity `

Anyone else having issues?

**Comment by bensinclair** [comment]
I have a feeling it's because there's no versions on the right hand side of https://packagist.org/packages/wolfcast/browser-detection. It just says `dev-master`.

If you look at this one https://packagist.org/packages/elvanto/api-php it has version `1.0.6`.

Not sure if that's the issue or not.

**Comment by Wolfcast** [comment]
It should be fixed now. I had to create a new tag that included composer.json. 1.4.0 should work now. Let me know if it works for you now,

**Comment by bensinclair** [comment]
We are close! It's now downloading which is great! 

One thing I just noticed (sorry I missed this earlier, I've only created a Packagist plugin once so I'm still learning msyelf) is your `composer.json` isn't telling the autoloader where to load the class from. 

If you add the following to your code, it should hopefully do the trick.

```
    "autoload": {
        "classmap": [
            "lib/"
        ]
    }
```

Full code:

```
{
    "name": "wolfcast/browser-detection",
    "type": "library",
    "description": "The Wolfcast BrowserDetection PHP class facilitates the identification of the user's environment such as Web browser, version, platform family, platform version or if it's a mobile device or not.",
    "keywords": ["browser","detection","version","environment","platform","mobile"],
    "homepage": "https://github.com/Wolfcast/BrowserDetection",
    "license": "GNU LGPL 3 or any later version",
    "authors": [
        {
            "name": "Alexandre Valiquette",
            "homepage": "http://wolfcast.com/",
            "role": "Main developer"
        }
    ],
    "require": {
        "php": ">=5.3.0"
    },
    "autoload": {
        "classmap": [
            "lib/"
        ]
    }
}
```

Hopefully that's everything!

**Comment by Wolfcast** [comment]
OK, recreated tag 2.4.0 which now includes autoloading. Let me know if everything works fine for you now.

**Comment by bensinclair** [comment]
Worked! Thank you! This now means users will not have to manually keep your repo up-to-date. Composer handles that ;)

**Comment by Wolfcast** [comment]
Yes thank you for having me add that feature to the project!
