### ISSUE TITLE
isTablet support

### ISSUE THREAD

**Issue by BassemN** [Wolfcast/BrowserDetection#8]
It will be great if you implemented isTablet method.

**Comment by Wolfcast** [comment]
It's a nice idea but that would be really hard to implement. The only ideas that I have would be based on data that would need to be updated frequently in the class otherwise new tablets won't be recognized as such...

**Comment by Wolfcast** [comment]
This will be supported in the next version (2.0) along more features.

**Comment by Wolfcast** [comment]
While a good idea on paper it would be impossible to catch accurately all types of tablets (and if I implement it, I would need to implement isPhone and such).
