### ISSUE TITLE
Test suite - user agents

### ISSUE THREAD

**Issue by ThaDafinser** [Wolfcast/BrowserDetection#9]
Hello,

in the readme there stands that this package was tested with `14252` user agents.
https://github.com/Wolfcast/BrowserDetection#features

Would it be possible to publish them here or seperate?

I would like to include your package in those 2 OS projects (but that needs #7 first)
https://github.com/ThaDafinser/UserAgentParser
https://github.com/ThaDafinser/UserAgentParserComparison

**Comment by Wolfcast** [comment]
I won't publish them here as I gathered them from various sources and I can't credit them since I don't remember where I got what but I can send them to you to help your test cases,

I will look into #7 soon so you can add them to your other projects.

**Comment by ThaDafinser** [comment]
User agent "only" i got over 2 millions. Do you have actual expected results for them?
The clue is that i use currently only UA which got actual expected results and i will display them on the comparison like on this example.

![image](https://cloud.githubusercontent.com/assets/533017/14272158/96b4a8e2-fb00-11e5-8f07-9238d8b61879.png)

**Comment by Wolfcast** [comment]
For most test cases I only have expected result for the browser name and version as the other detection features were added later (I would have to manually check them one by one to validate them).

**Comment by ThaDafinser** [comment]
@Wolfcast if you have something with expected results you can publish in your repo, i would be happy to use it for the comparison.

Most important first would be the publishing through https://packagist.org/ so we could use this package easily.

Thanks in advance

**Comment by Wolfcast** [comment]
Packagist/Composer now supported with release 2.4.0.

As for my UAs find them here in a zip file:
http://tinyurl.com/jsdtt4p

Let me know when it's downloaded on your side so I can delete the zip.

**Comment by ThaDafinser** [comment]
@Wolfcast thank you i downloaded it.

But i would recommend to publish it in this repo, there are many reasons to do it:
- CI testing with travis
- other people can add/correct tests
- other people can learn from it

**Comment by Wolfcast** [comment]
Yes I understand and I will add it to the repo in the future but first I must refactor it and expand the test results beyond only the browser name & version. Once done I will (re)publish it.
